#ifndef BOBLBOBL_DIPSWITCHES_H
#define BOBLBOBL_DIPSWITCHES_H

// ==========================================================================
// boblbobl_dipswitches.h  --  GENERATED by tools/dipswitches/dipgen.py
// Source: `mame -listxml boblbobl`  (0.289 (mame0289))
//
// -listxml is MAME resolving the exact ioport this game's GAME/GAMEL line
// uses, after every PORT_INCLUDE / PORT_MODIFY -- so these values are the
// real ones for THIS set, not a hand-read of the wrong INPUT_PORTS block.
//
// Each <TAG>_DEFAULT below = OR of every dipvalue marked default="yes".
// 'Unused' switches (PORT_DIPUNUSED_DIPLOC) default to their bit SET, i.e.
// they read HIGH -- same as an unwired DIP line on real hardware.
//
// Re-run dipgen.py to regenerate. Hand-edit only the SELECTED #defines
// (below each switch) if you want a non-default machine configuration.
// ==========================================================================

// --------------------------------------------------------------------------
// DSW0   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW0:?  Flip Screen  (bits 0x02)
//    Off                          = 0x02   // default
#define BOBLBOBL_DSW0_FLIP_SCREEN_OFF                        0x02
//    On                           = 0x00
#define BOBLBOBL_DSW0_FLIP_SCREEN_ON                         0x00
#define BOBLBOBL_DSW0_FLIP_SCREEN_SELECTED                   BOBLBOBL_DSW0_FLIP_SCREEN_OFF

//  DSW0:?  Mode  (bits 0x05)
//    Game, English                = 0x04   // default
#define BOBLBOBL_DSW0_MODE_GAME_ENGLISH                      0x04
//    Game, Japanese               = 0x05
#define BOBLBOBL_DSW0_MODE_GAME_JAPANESE                     0x05
//    Test (Grid and Inputs)       = 0x01
#define BOBLBOBL_DSW0_MODE_TEST_GRID_AND_INPUTS              0x01
//    Test (RAM and Sound)         = 0x00
#define BOBLBOBL_DSW0_MODE_TEST_RAM_AND_SOUND                0x00
#define BOBLBOBL_DSW0_MODE_SELECTED                          BOBLBOBL_DSW0_MODE_GAME_ENGLISH

//  DSW0:?  Demo Sounds  (bits 0x08)
//    Off                          = 0x00
#define BOBLBOBL_DSW0_DEMO_SOUNDS_OFF                        0x00
//    On                           = 0x08   // default
#define BOBLBOBL_DSW0_DEMO_SOUNDS_ON                         0x08
#define BOBLBOBL_DSW0_DEMO_SOUNDS_SELECTED                   BOBLBOBL_DSW0_DEMO_SOUNDS_ON

//  DSW0:?  Coin A  (bits 0x30)
//    2 Coins/1 Credit             = 0x10
#define BOBLBOBL_DSW0_COIN_A_2_COINS_1_CREDIT                0x10
//    1 Coin/1 Credit              = 0x30   // default
#define BOBLBOBL_DSW0_COIN_A_1_COIN_1_CREDIT                 0x30
//    2 Coins/3 Credits            = 0x00
#define BOBLBOBL_DSW0_COIN_A_2_COINS_3_CREDITS               0x00
//    1 Coin/2 Credits             = 0x20
#define BOBLBOBL_DSW0_COIN_A_1_COIN_2_CREDITS                0x20
#define BOBLBOBL_DSW0_COIN_A_SELECTED                        BOBLBOBL_DSW0_COIN_A_1_COIN_1_CREDIT

//  DSW0:?  Coin B  (bits 0xc0)
//    2 Coins/1 Credit             = 0x40
#define BOBLBOBL_DSW0_COIN_B_2_COINS_1_CREDIT                0x40
//    1 Coin/1 Credit              = 0xc0   // default
#define BOBLBOBL_DSW0_COIN_B_1_COIN_1_CREDIT                 0xc0
//    2 Coins/3 Credits            = 0x00
#define BOBLBOBL_DSW0_COIN_B_2_COINS_3_CREDITS               0x00
//    1 Coin/2 Credits             = 0x80
#define BOBLBOBL_DSW0_COIN_B_1_COIN_2_CREDITS                0x80
#define BOBLBOBL_DSW0_COIN_B_SELECTED                        BOBLBOBL_DSW0_COIN_B_1_COIN_1_CREDIT

// DSW0 power-on byte (all switches at MAME default = 0xfe)
#define BOBLBOBL_DSW0_DEFAULT ( \
  BOBLBOBL_DSW0_FLIP_SCREEN_SELECTED | \
  BOBLBOBL_DSW0_MODE_SELECTED | \
  BOBLBOBL_DSW0_DEMO_SOUNDS_SELECTED | \
  BOBLBOBL_DSW0_COIN_A_SELECTED | \
  BOBLBOBL_DSW0_COIN_B_SELECTED   \
  )
// == 0xfe

// --------------------------------------------------------------------------
// DSW1   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW1:?  Difficulty  (bits 0x03)
//    Easy                         = 0x02
#define BOBLBOBL_DSW1_DIFFICULTY_EASY                        0x02
//    Normal                       = 0x03   // default
#define BOBLBOBL_DSW1_DIFFICULTY_NORMAL                      0x03
//    Hard                         = 0x01
#define BOBLBOBL_DSW1_DIFFICULTY_HARD                        0x01
//    Very Hard                    = 0x00
#define BOBLBOBL_DSW1_DIFFICULTY_VERY_HARD                   0x00
#define BOBLBOBL_DSW1_DIFFICULTY_SELECTED                    BOBLBOBL_DSW1_DIFFICULTY_EASY

//  DSW1:?  Bonus Life  (bits 0x0c)
//    20K 80K 300K                 = 0x08
#define BOBLBOBL_DSW1_BONUS_LIFE_20K_80K_300K                0x08
//    30K 100K 400K                = 0x0c   // default
#define BOBLBOBL_DSW1_BONUS_LIFE_30K_100K_400K               0x0c
//    40K 200K 500K                = 0x04
#define BOBLBOBL_DSW1_BONUS_LIFE_40K_200K_500K               0x04
//    50K 250K 500K                = 0x00
#define BOBLBOBL_DSW1_BONUS_LIFE_50K_250K_500K               0x00
#define BOBLBOBL_DSW1_BONUS_LIFE_SELECTED                    BOBLBOBL_DSW1_BONUS_LIFE_20K_80K_300K

//  DSW1:?  Lives  (bits 0x30)
//    1                            = 0x10
#define BOBLBOBL_DSW1_LIVES_1                                0x10
//    2                            = 0x00
#define BOBLBOBL_DSW1_LIVES_2                                0x00
//    3                            = 0x30   // default
#define BOBLBOBL_DSW1_LIVES_3                                0x30
//    5                            = 0x20
#define BOBLBOBL_DSW1_LIVES_5                                0x20
#define BOBLBOBL_DSW1_LIVES_SELECTED                         BOBLBOBL_DSW1_LIVES_3

//  DSW1:?  Monster Speed  (bits 0xc0)
//    Normal                       = 0x00   // default
#define BOBLBOBL_DSW1_MONSTER_SPEED_NORMAL                   0x00
//    Medium                       = 0x40
#define BOBLBOBL_DSW1_MONSTER_SPEED_MEDIUM                   0x40
//    High                         = 0x80
#define BOBLBOBL_DSW1_MONSTER_SPEED_HIGH                     0x80
//    Very High                    = 0xc0
#define BOBLBOBL_DSW1_MONSTER_SPEED_VERY_HIGH                0xc0
#define BOBLBOBL_DSW1_MONSTER_SPEED_SELECTED                 BOBLBOBL_DSW1_MONSTER_SPEED_NORMAL

// DSW1 power-on byte (all switches at MAME default = 0x3f)
#define BOBLBOBL_DSW1_DEFAULT ( \
  BOBLBOBL_DSW1_DIFFICULTY_SELECTED | \
  BOBLBOBL_DSW1_BONUS_LIFE_SELECTED | \
  BOBLBOBL_DSW1_LIVES_SELECTED | \
  BOBLBOBL_DSW1_MONSTER_SPEED_SELECTED   \
  )
// == 0x3f

#endif
