#ifndef ARKANOID_DIPSWITCHES_H
#define ARKANOID_DIPSWITCHES_H

// ==========================================================================
// arkanoid_dipswitches.h  --  GENERATED by tools/dipswitches/dipgen.py
// Source: `mame -listxml arkanoid`  (0.289 (mame0289))
//
// -listxml is MAME resolving the exact ioport this game's GAME/GAMEL line
// uses, after every PORT_INCLUDE / PORT_MODIFY -- so these values are the
// real ones for THIS set, not a hand-read of the wrong INPUT_PORTS block.
//
// Each <TAG>_DEFAULT below = OR of every dipvalue marked default="yes".
// 'Unused' switches (PORT_DIPUNUSED_DIPLOC) default to their bit SET, i.e.
// they read HIGH -- same as an unwired DIP line on real hardware.
//
// Re-run dipgen.py to regenerate. Hand-edit only the SELECTED #defines
// (below each switch) if you want a non-default machine configuration.
// ==========================================================================

// --------------------------------------------------------------------------
// DSW   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW:1+2  Coinage  (bits 0xc0)
//    2 Coins/1 Credit             = 0x40
#define ARKANOID_DSW_COINAGE_2_COINS_1_CREDIT                0x40
//    1 Coin/1 Credit              = 0xc0   // default
#define ARKANOID_DSW_COINAGE_1_COIN_1_CREDIT                 0xc0
//    1 Coin/2 Credits             = 0x80
#define ARKANOID_DSW_COINAGE_1_COIN_2_CREDITS                0x80
//    1 Coin/6 Credits             = 0x00
#define ARKANOID_DSW_COINAGE_1_COIN_6_CREDITS                0x00
#define ARKANOID_DSW_COINAGE_SELECTED                        ARKANOID_DSW_COINAGE_1_COIN_1_CREDIT

//  DSW:3  Lives  (bits 0x20)
//    3                            = 0x20   // default
#define ARKANOID_DSW_LIVES_3                                 0x20
//    5                            = 0x00
#define ARKANOID_DSW_LIVES_5                                 0x00
#define ARKANOID_DSW_LIVES_SELECTED                          ARKANOID_DSW_LIVES_5

//  DSW:4  Bonus Life  (bits 0x10)
//    20K 60K 60K+                 = 0x10   // default
#define ARKANOID_DSW_BONUS_LIFE_20K_60K_60K                  0x10
//    20K                          = 0x00
#define ARKANOID_DSW_BONUS_LIFE_20K                          0x00
#define ARKANOID_DSW_BONUS_LIFE_SELECTED                     ARKANOID_DSW_BONUS_LIFE_20K_60K_60K

//  DSW:5  Difficulty  (bits 0x08)
//    Easy                         = 0x08   // default
#define ARKANOID_DSW_DIFFICULTY_EASY                         0x08
//    Hard                         = 0x00
#define ARKANOID_DSW_DIFFICULTY_HARD                         0x00
#define ARKANOID_DSW_DIFFICULTY_SELECTED                     ARKANOID_DSW_DIFFICULTY_EASY

//  DSW:6  Service Mode  (bits 0x04)
//    Off                          = 0x04   // default
#define ARKANOID_DSW_SERVICE_MODE_OFF                        0x04
//    On                           = 0x00
#define ARKANOID_DSW_SERVICE_MODE_ON                         0x00
#define ARKANOID_DSW_SERVICE_MODE_SELECTED                   ARKANOID_DSW_SERVICE_MODE_OFF

//  DSW:7  Flip Screen  (bits 0x02)
//    Off                          = 0x02   // default
#define ARKANOID_DSW_FLIP_SCREEN_OFF                         0x02
//    On                           = 0x00
#define ARKANOID_DSW_FLIP_SCREEN_ON                          0x00
#define ARKANOID_DSW_FLIP_SCREEN_SELECTED                    ARKANOID_DSW_FLIP_SCREEN_OFF

//  DSW:8  Allow Continue  (bits 0x01)
//    No                           = 0x01
#define ARKANOID_DSW_ALLOW_CONTINUE_NO                       0x01
//    Yes                          = 0x00   // default
#define ARKANOID_DSW_ALLOW_CONTINUE_YES                      0x00
#define ARKANOID_DSW_ALLOW_CONTINUE_SELECTED                 ARKANOID_DSW_ALLOW_CONTINUE_YES

// DSW power-on byte (all switches at MAME default = 0xfe)
#define ARKANOID_DSW_DEFAULT ( \
  ARKANOID_DSW_COINAGE_SELECTED | \
  ARKANOID_DSW_LIVES_SELECTED | \
  ARKANOID_DSW_BONUS_LIFE_SELECTED | \
  ARKANOID_DSW_DIFFICULTY_SELECTED | \
  ARKANOID_DSW_SERVICE_MODE_SELECTED | \
  ARKANOID_DSW_FLIP_SCREEN_SELECTED | \
  ARKANOID_DSW_ALLOW_CONTINUE_SELECTED   \
  )
// == 0xfe

#endif
