#ifndef GNG_DIPSWITCHES_H
#define GNG_DIPSWITCHES_H

// ==========================================================================
// gng_dipswitches.h  --  GENERATED by tools/dipswitches/dipgen.py
// Source: `mame -listxml gng`  (0.289 (mame0289))
//
// -listxml is MAME resolving the exact ioport this game's GAME/GAMEL line
// uses, after every PORT_INCLUDE / PORT_MODIFY -- so these values are the
// real ones for THIS set, not a hand-read of the wrong INPUT_PORTS block.
//
// Each <TAG>_DEFAULT below = OR of every dipvalue marked default="yes".
// 'Unused' switches (PORT_DIPUNUSED_DIPLOC) default to their bit SET, i.e.
// they read HIGH -- same as an unwired DIP line on real hardware.
//
// Re-run dipgen.py to regenerate. Hand-edit only the SELECTED #defines
// (below each switch) if you want a non-default machine configuration.
// ==========================================================================

// --------------------------------------------------------------------------
// DSW1   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW1:1  Flip Screen  (bits 0x80)
//    Off                          = 0x80   // default
#define GNG_DSW1_FLIP_SCREEN_OFF                             0x80
//    On                           = 0x00
#define GNG_DSW1_FLIP_SCREEN_ON                              0x00
#define GNG_DSW1_FLIP_SCREEN_SELECTED                        GNG_DSW1_FLIP_SCREEN_ON
// having GNG_DSW1_FLIP_SCREEN_ON cuts off the top of the HUD text (score/lives).

//  DSW1:2  Service Mode  (bits 0x40)
//    Off                          = 0x40   // default
#define GNG_DSW1_SERVICE_MODE_OFF                            0x40
//    On                           = 0x00
#define GNG_DSW1_SERVICE_MODE_ON                             0x00
#define GNG_DSW1_SERVICE_MODE_SELECTED                       GNG_DSW1_SERVICE_MODE_OFF

//  DSW1:3  Demo Sounds  (bits 0x20)
//    Off                          = 0x20
#define GNG_DSW1_DEMO_SOUNDS_OFF                             0x20
//    On                           = 0x00   // default
#define GNG_DSW1_DEMO_SOUNDS_ON                              0x00
#define GNG_DSW1_DEMO_SOUNDS_SELECTED                        GNG_DSW1_DEMO_SOUNDS_ON

//  DSW1:4  Coinage affects  (bits 0x10)
//    Coin A                       = 0x10   // default
#define GNG_DSW1_COINAGE_AFFECTS_COIN_A                      0x10
//    Coin B                       = 0x00
#define GNG_DSW1_COINAGE_AFFECTS_COIN_B                      0x00
#define GNG_DSW1_COINAGE_AFFECTS_SELECTED                    GNG_DSW1_COINAGE_AFFECTS_COIN_A

//  DSW1:8+7+6+5  Coinage  (bits 0x0f)
//    4 Coins/1 Credit             = 0x02
#define GNG_DSW1_COINAGE_4_COINS_1_CREDIT                    0x02
//    3 Coins/1 Credit             = 0x05
#define GNG_DSW1_COINAGE_3_COINS_1_CREDIT                    0x05
//    2 Coins/1 Credit             = 0x08
#define GNG_DSW1_COINAGE_2_COINS_1_CREDIT                    0x08
//    3 Coins/2 Credits            = 0x04
#define GNG_DSW1_COINAGE_3_COINS_2_CREDITS                   0x04
//    4 Coins/3 Credits            = 0x01
#define GNG_DSW1_COINAGE_4_COINS_3_CREDITS                   0x01
//    1 Coin/1 Credit              = 0x0f   // default
#define GNG_DSW1_COINAGE_1_COIN_1_CREDIT                     0x0f
//    3 Coins/4 Credits            = 0x03
#define GNG_DSW1_COINAGE_3_COINS_4_CREDITS                   0x03
//    2 Coins/3 Credits            = 0x07
#define GNG_DSW1_COINAGE_2_COINS_3_CREDITS                   0x07
//    1 Coin/2 Credits             = 0x0e
#define GNG_DSW1_COINAGE_1_COIN_2_CREDITS                    0x0e
//    2 Coins/5 Credits            = 0x06
#define GNG_DSW1_COINAGE_2_COINS_5_CREDITS                   0x06
//    1 Coin/3 Credits             = 0x0d
#define GNG_DSW1_COINAGE_1_COIN_3_CREDITS                    0x0d
//    1 Coin/4 Credits             = 0x0c
#define GNG_DSW1_COINAGE_1_COIN_4_CREDITS                    0x0c
//    1 Coin/5 Credits             = 0x0b
#define GNG_DSW1_COINAGE_1_COIN_5_CREDITS                    0x0b
//    1 Coin/6 Credits             = 0x0a
#define GNG_DSW1_COINAGE_1_COIN_6_CREDITS                    0x0a
//    1 Coin/7 Credits             = 0x09
#define GNG_DSW1_COINAGE_1_COIN_7_CREDITS                    0x09
//    Free Play                    = 0x00
#define GNG_DSW1_COINAGE_FREE_PLAY                           0x00
#define GNG_DSW1_COINAGE_SELECTED                            GNG_DSW1_COINAGE_1_COIN_1_CREDIT

// DSW1 power-on byte (all switches at MAME default = 0xdf)
#define GNG_DSW1_DEFAULT ( \
  GNG_DSW1_FLIP_SCREEN_SELECTED | \
  GNG_DSW1_SERVICE_MODE_SELECTED | \
  GNG_DSW1_DEMO_SOUNDS_SELECTED | \
  GNG_DSW1_COINAGE_AFFECTS_SELECTED | \
  GNG_DSW1_COINAGE_SELECTED   \
  )
// == 0xdf

// --------------------------------------------------------------------------
// DSW2   (port mask 0xff)
// --------------------------------------------------------------------------
//  DSW2:1  Unused  (bits 0x80)
//    Off                          = 0x80   // default
#define GNG_DSW2_UNUSED_OFF                                  0x80
//    On                           = 0x00
#define GNG_DSW2_UNUSED_ON                                   0x00
#define GNG_DSW2_UNUSED_SELECTED                             GNG_DSW2_UNUSED_OFF

//  DSW2:3+2  Difficulty  (bits 0x60)
//    Easy                         = 0x40
#define GNG_DSW2_DIFFICULTY_EASY                             0x40
//    Normal                       = 0x60   // default
#define GNG_DSW2_DIFFICULTY_NORMAL                           0x60
//    Difficult                    = 0x20
#define GNG_DSW2_DIFFICULTY_DIFFICULT                        0x20
//    Very Difficult               = 0x00
#define GNG_DSW2_DIFFICULTY_VERY_DIFFICULT                   0x00
#define GNG_DSW2_DIFFICULTY_SELECTED                         GNG_DSW2_DIFFICULTY_EASY

//  DSW2:5+4  Bonus Life  (bits 0x18)
//    20K 70K Every 70K            = 0x18   // default
#define GNG_DSW2_BONUS_LIFE_20K_70K_EVERY_70K                0x18
//    30K 80K Every 80K            = 0x10
#define GNG_DSW2_BONUS_LIFE_30K_80K_EVERY_80K                0x10
//    20K and 80K Only             = 0x08
#define GNG_DSW2_BONUS_LIFE_20K_AND_80K_ONLY                 0x08
//    30K and 80K Only             = 0x00
#define GNG_DSW2_BONUS_LIFE_30K_AND_80K_ONLY                 0x00
#define GNG_DSW2_BONUS_LIFE_SELECTED                         GNG_DSW2_BONUS_LIFE_20K_70K_EVERY_70K

//  DSW2:6  Cabinet  (bits 0x04)
//    Upright                      = 0x00   // default
#define GNG_DSW2_CABINET_UPRIGHT                             0x00
//    Cocktail                     = 0x04
#define GNG_DSW2_CABINET_COCKTAIL                            0x04
#define GNG_DSW2_CABINET_SELECTED                            GNG_DSW2_CABINET_UPRIGHT
// GNG_DSW2_CABINET_COCKTAIL doe not work in galaginoplus

//  DSW2:8+7  Lives  (bits 0x03)
//    3                            = 0x03   // default
#define GNG_DSW2_LIVES_3                                     0x03
//    4                            = 0x02
#define GNG_DSW2_LIVES_4                                     0x02
//    5                            = 0x01
#define GNG_DSW2_LIVES_5                                     0x01
//    7                            = 0x00
#define GNG_DSW2_LIVES_7                                     0x00
#define GNG_DSW2_LIVES_SELECTED                              GNG_DSW2_LIVES_7

// DSW2 power-on byte (all switches at MAME default = 0xfb)
#define GNG_DSW2_DEFAULT ( \
  GNG_DSW2_UNUSED_SELECTED | \
  GNG_DSW2_DIFFICULTY_SELECTED | \
  GNG_DSW2_BONUS_LIFE_SELECTED | \
  GNG_DSW2_CABINET_SELECTED | \
  GNG_DSW2_LIVES_SELECTED   \
  )
// == 0xfb

#endif
