#ifndef FLSTORY_DIPSWITCHES_H
#define FLSTORY_DIPSWITCHES_H

// ==========================================================================
// flstory_dipswitches.h  --  GENERATED by tools/dipswitches/dipgen.py
// Source: `mame -listxml flstory`  (0.289 (mame0289))
//
// -listxml is MAME resolving the exact ioport this game's GAME/GAMEL line
// uses, after every PORT_INCLUDE / PORT_MODIFY -- so these values are the
// real ones for THIS set, not a hand-read of the wrong INPUT_PORTS block.
//
// Each <TAG>_DEFAULT below = OR of every dipvalue marked default="yes".
// 'Unused' switches (PORT_DIPUNUSED_DIPLOC) default to their bit SET, i.e.
// they read HIGH -- same as an unwired DIP line on real hardware.
//
// Re-run dipgen.py to regenerate. Hand-edit only the SELECTED #defines
// (below each switch) if you want a non-default machine configuration.
// ==========================================================================

// --------------------------------------------------------------------------
// SWA   (port mask 0xff)
// --------------------------------------------------------------------------
//  SWA:1+2  Bonus Life  (bits 0x03)
//    30000 100000                 = 0x00   // default
#define FLSTORY_SWA_BONUS_LIFE_30000_100000                  0x00
//    30000 150000                 = 0x01
#define FLSTORY_SWA_BONUS_LIFE_30000_150000                  0x01
//    50000 150000                 = 0x02
#define FLSTORY_SWA_BONUS_LIFE_50000_150000                  0x02
//    70000 150000                 = 0x03
#define FLSTORY_SWA_BONUS_LIFE_70000_150000                  0x03
#define FLSTORY_SWA_BONUS_LIFE_SELECTED                      FLSTORY_SWA_BONUS_LIFE_30000_100000

//  SWA:3  Free Play  (bits 0x04)
//    Off                          = 0x04   // default
#define FLSTORY_SWA_FREE_PLAY_OFF                            0x04
//    On                           = 0x00
#define FLSTORY_SWA_FREE_PLAY_ON                             0x00
#define FLSTORY_SWA_FREE_PLAY_SELECTED                       FLSTORY_SWA_FREE_PLAY_OFF

//  SWA:4+5  Lives  (bits 0x18)
//    3                            = 0x08   // default
#define FLSTORY_SWA_LIVES_3                                  0x08
//    4                            = 0x10
#define FLSTORY_SWA_LIVES_4                                  0x10
//    5                            = 0x18
#define FLSTORY_SWA_LIVES_5                                  0x18
//    Infinite (Cheat)             = 0x00
#define FLSTORY_SWA_LIVES_INFINITE_CHEAT                     0x00
#define FLSTORY_SWA_LIVES_SELECTED                           FLSTORY_SWA_LIVES_3

//  SWA:6  Debug Mode  (bits 0x20)
//    Off                          = 0x20   // default
#define FLSTORY_SWA_DEBUG_MODE_OFF                           0x20
//    On                           = 0x00
#define FLSTORY_SWA_DEBUG_MODE_ON                            0x00
#define FLSTORY_SWA_DEBUG_MODE_SELECTED                      FLSTORY_SWA_DEBUG_MODE_OFF

//  SWA:7  Flip Screen  (bits 0x40)
//    Off                          = 0x40   // default
#define FLSTORY_SWA_FLIP_SCREEN_OFF                          0x40
//    On                           = 0x00
#define FLSTORY_SWA_FLIP_SCREEN_ON                           0x00
#define FLSTORY_SWA_FLIP_SCREEN_SELECTED                     FLSTORY_SWA_FLIP_SCREEN_ON

//  SWA:8  Cabinet  (bits 0x80)
//    Upright                      = 0x80   // default
#define FLSTORY_SWA_CABINET_UPRIGHT                          0x80
//    Cocktail                     = 0x00
#define FLSTORY_SWA_CABINET_COCKTAIL                         0x00
#define FLSTORY_SWA_CABINET_SELECTED                         FLSTORY_SWA_CABINET_UPRIGHT

// SWA power-on byte (all switches at MAME default = 0xec)
#define FLSTORY_SWA_DEFAULT ( \
  FLSTORY_SWA_BONUS_LIFE_SELECTED | \
  FLSTORY_SWA_FREE_PLAY_SELECTED | \
  FLSTORY_SWA_LIVES_SELECTED | \
  FLSTORY_SWA_DEBUG_MODE_SELECTED | \
  FLSTORY_SWA_FLIP_SCREEN_SELECTED | \
  FLSTORY_SWA_CABINET_SELECTED   \
  )
// == 0xec

// --------------------------------------------------------------------------
// SWB   (port mask 0xff)
// --------------------------------------------------------------------------
//  SWB:1+2+3+4  Coin A  (bits 0x0f)
//    9 Coins/1 Credit             = 0x0f
#define FLSTORY_SWB_COIN_A_9_COINS_1_CREDIT                  0x0f
//    8 Coins/1 Credit             = 0x0e
#define FLSTORY_SWB_COIN_A_8_COINS_1_CREDIT                  0x0e
//    7 Coins/1 Credit             = 0x0d
#define FLSTORY_SWB_COIN_A_7_COINS_1_CREDIT                  0x0d
//    6 Coins/1 Credit             = 0x0c
#define FLSTORY_SWB_COIN_A_6_COINS_1_CREDIT                  0x0c
//    5 Coins/1 Credit             = 0x0b
#define FLSTORY_SWB_COIN_A_5_COINS_1_CREDIT                  0x0b
//    4 Coins/1 Credit             = 0x0a
#define FLSTORY_SWB_COIN_A_4_COINS_1_CREDIT                  0x0a
//    3 Coins/1 Credit             = 0x09
#define FLSTORY_SWB_COIN_A_3_COINS_1_CREDIT                  0x09
//    2 Coins/1 Credit             = 0x08
#define FLSTORY_SWB_COIN_A_2_COINS_1_CREDIT                  0x08
//    1 Coin/1 Credit              = 0x00   // default
#define FLSTORY_SWB_COIN_A_1_COIN_1_CREDIT                   0x00
//    1 Coin/2 Credits             = 0x01
#define FLSTORY_SWB_COIN_A_1_COIN_2_CREDITS                  0x01
//    1 Coin/3 Credits             = 0x02
#define FLSTORY_SWB_COIN_A_1_COIN_3_CREDITS                  0x02
//    1 Coin/4 Credits             = 0x03
#define FLSTORY_SWB_COIN_A_1_COIN_4_CREDITS                  0x03
//    1 Coin/5 Credits             = 0x04
#define FLSTORY_SWB_COIN_A_1_COIN_5_CREDITS                  0x04
//    1 Coin/6 Credits             = 0x05
#define FLSTORY_SWB_COIN_A_1_COIN_6_CREDITS                  0x05
//    1 Coin/7 Credits             = 0x06
#define FLSTORY_SWB_COIN_A_1_COIN_7_CREDITS                  0x06
//    1 Coin/8 Credits             = 0x07
#define FLSTORY_SWB_COIN_A_1_COIN_8_CREDITS                  0x07
#define FLSTORY_SWB_COIN_A_SELECTED                          FLSTORY_SWB_COIN_A_1_COIN_1_CREDIT

//  SWB:5+6+7+8  Coin B  (bits 0xf0)
//    9 Coins/1 Credit             = 0xf0
#define FLSTORY_SWB_COIN_B_9_COINS_1_CREDIT                  0xf0
//    8 Coins/1 Credit             = 0xe0
#define FLSTORY_SWB_COIN_B_8_COINS_1_CREDIT                  0xe0
//    7 Coins/1 Credit             = 0xd0
#define FLSTORY_SWB_COIN_B_7_COINS_1_CREDIT                  0xd0
//    6 Coins/1 Credit             = 0xc0
#define FLSTORY_SWB_COIN_B_6_COINS_1_CREDIT                  0xc0
//    5 Coins/1 Credit             = 0xb0
#define FLSTORY_SWB_COIN_B_5_COINS_1_CREDIT                  0xb0
//    4 Coins/1 Credit             = 0xa0
#define FLSTORY_SWB_COIN_B_4_COINS_1_CREDIT                  0xa0
//    3 Coins/1 Credit             = 0x90
#define FLSTORY_SWB_COIN_B_3_COINS_1_CREDIT                  0x90
//    2 Coins/1 Credit             = 0x80
#define FLSTORY_SWB_COIN_B_2_COINS_1_CREDIT                  0x80
//    1 Coin/1 Credit              = 0x00   // default
#define FLSTORY_SWB_COIN_B_1_COIN_1_CREDIT                   0x00
//    1 Coin/2 Credits             = 0x10
#define FLSTORY_SWB_COIN_B_1_COIN_2_CREDITS                  0x10
//    1 Coin/3 Credits             = 0x20
#define FLSTORY_SWB_COIN_B_1_COIN_3_CREDITS                  0x20
//    1 Coin/4 Credits             = 0x30
#define FLSTORY_SWB_COIN_B_1_COIN_4_CREDITS                  0x30
//    1 Coin/5 Credits             = 0x40
#define FLSTORY_SWB_COIN_B_1_COIN_5_CREDITS                  0x40
//    1 Coin/6 Credits             = 0x50
#define FLSTORY_SWB_COIN_B_1_COIN_6_CREDITS                  0x50
//    1 Coin/7 Credits             = 0x60
#define FLSTORY_SWB_COIN_B_1_COIN_7_CREDITS                  0x60
//    1 Coin/8 Credits             = 0x70
#define FLSTORY_SWB_COIN_B_1_COIN_8_CREDITS                  0x70
#define FLSTORY_SWB_COIN_B_SELECTED                          FLSTORY_SWB_COIN_B_1_COIN_1_CREDIT

// SWB power-on byte (all switches at MAME default = 0x00)
#define FLSTORY_SWB_DEFAULT ( \
  FLSTORY_SWB_COIN_A_SELECTED | \
  FLSTORY_SWB_COIN_B_SELECTED   \
  )
// == 0x00

// --------------------------------------------------------------------------
// SWC   (port mask 0xff)
// --------------------------------------------------------------------------
//  SWC:1+2+3  Unused  (bits 0x07)
//    Off                          = 0x00   // default
#define FLSTORY_SWC_UNUSED_OFF                               0x00
//    On                           = 0x07
#define FLSTORY_SWC_UNUSED_ON                                0x07
#define FLSTORY_SWC_UNUSED_SELECTED                          FLSTORY_SWC_UNUSED_OFF

//  SWC:4  Allow Continue  (bits 0x08)
//    No                           = 0x00
#define FLSTORY_SWC_ALLOW_CONTINUE_NO                        0x00
//    Yes                          = 0x08   // default
#define FLSTORY_SWC_ALLOW_CONTINUE_YES                       0x08
#define FLSTORY_SWC_ALLOW_CONTINUE_SELECTED                  FLSTORY_SWC_ALLOW_CONTINUE_YES

//  SWC:5  Attract Animation  (bits 0x10)
//    Off                          = 0x00
#define FLSTORY_SWC_ATTRACT_ANIMATION_OFF                    0x00
//    On                           = 0x10   // default
#define FLSTORY_SWC_ATTRACT_ANIMATION_ON                     0x10
#define FLSTORY_SWC_ATTRACT_ANIMATION_SELECTED               FLSTORY_SWC_ATTRACT_ANIMATION_ON

//  SWC:6  Leave Off  (bits 0x20)
//    Off                          = 0x20   // default
#define FLSTORY_SWC_LEAVE_OFF_OFF                            0x20
//    On                           = 0x00
#define FLSTORY_SWC_LEAVE_OFF_ON                             0x00
#define FLSTORY_SWC_LEAVE_OFF_SELECTED                       FLSTORY_SWC_LEAVE_OFF_OFF

//  SWC:7  Invulnerability (Cheat)  (bits 0x40)
//    Off                          = 0x40   // default
#define FLSTORY_SWC_INVULNERABILITY_CHEAT_OFF                0x40
//    On                           = 0x00
#define FLSTORY_SWC_INVULNERABILITY_CHEAT_ON                 0x00
#define FLSTORY_SWC_INVULNERABILITY_CHEAT_SELECTED           FLSTORY_SWC_INVULNERABILITY_CHEAT_OFF

//  SWC:8  Coin Slots  (bits 0x80)
//    1                            = 0x00
#define FLSTORY_SWC_COIN_SLOTS_1                             0x00
//    2                            = 0x80   // default
#define FLSTORY_SWC_COIN_SLOTS_2                             0x80
#define FLSTORY_SWC_COIN_SLOTS_SELECTED                      FLSTORY_SWC_COIN_SLOTS_2

// SWC power-on byte (all switches at MAME default = 0xf8)
#define FLSTORY_SWC_DEFAULT ( \
  FLSTORY_SWC_UNUSED_SELECTED | \
  FLSTORY_SWC_ALLOW_CONTINUE_SELECTED | \
  FLSTORY_SWC_ATTRACT_ANIMATION_SELECTED | \
  FLSTORY_SWC_LEAVE_OFF_SELECTED | \
  FLSTORY_SWC_INVULNERABILITY_CHEAT_SELECTED | \
  FLSTORY_SWC_COIN_SLOTS_SELECTED   \
  )
// == 0xf8

#endif
