#!/usr/bin/env python3
# ============================================================
# flstory_romconv_all.py
#
# One-shot ROM converter for the Galagino Plus `flstory` machine.
# The `flstory` machine IS MAME `flstory` = "The FairyLand Story" (Taito,
# 1985, Z80 main + Z80 audio + MC68705P5 protection MCU + AY-8910 +
# MSM5232 + DAC, ROT180). MAME driver: src/mame/taito/flstory.cpp.
#
# Self-contained (same style/shape as gng/conv_gng-all.py). Meant to be run
# from this directory (src/machines/flstory/) or anywhere else - all paths
# below are resolved relative to this script's own location, so the
# working directory does not matter:
#
#     cd GalaginoPlus-main\source\src\machines\flstory
#     python flstory_romconv_all.py
#
# With no arguments it reads GalaginoPlus-main\romszip\flstory.zip and
# (re)writes every ROM-derived header directly into this directory (next
# to this script). It verifies every size + CRC32 against the MAME
# `flstory` (parent) set first, so a wrong/renamed dump is caught early.
#
# USAGE
#     python flstory_romconv_all.py [ROMSRC] [-o OUTDIR] [--no-verify] [--no-preview]
#
#     ROMSRC   flstory.zip, OR a folder holding the loose ROM files
#              (default: ../../../../romszip/flstory.zip relative to
#              this script, i.e. GalaginoPlus-main/romszip/flstory.zip)
#     -o       output folder for the .h files (default: this directory)
#
# INPUT FILES  (MAME `flstory` parent set - `mame flstory -verifyroms` must
# pass; sizes/CRC32s below cross-checked against
# source/src/machines/flstory/crc_check.txt, which was hand-copied from the
# same MAME set)
#     cpu-a45.15/.16/.17     maincpu   3 x 0x4000  (0x0000/0x4000/0x8000)
#     snd.22 snd.23          audiocpu  2 x 0x2000  (0x0000/0x2000)
#     a45-20.mcu             bmcu:mcu  0x0800
#     vid-a45.18/.06/.08/.20/.19/.07/.09/.21
#                            tiles     8 x 0x4000, ROM_REGION(...,
#                            ROMREGION_INVERT) - MAME bit-inverts (XOR 0xFF)
#                            every byte of this region AFTER loading, before
#                            gfxdecode ever sees it. See "concrete bug fixed"
#                            note below - the previous generic-tool output
#                            (flstory_tiles.h, from tools/romconv/
#                            romextract.py) did NOT apply this and is wrong.
#
# OUTPUT HEADERS  (written to OUTDIR, i.e. this directory by default)
#     flstory_rom.h        const unsigned char flstory_rom[65536]
#                             cpu-a45.15 @0x0000, .16 @0x4000, .17 @0x8000,
#                             0x8000 bytes of real ROM; 0xc000-0xffff = 0xFF
#                             pad (never fetched - the CPU map's ROM window
#                             is only 0x0000-0xbfff, and only 0x0000-0xbfff
#                             is actually populated here: 3*0x4000=0xc000).
#     flstory_audiocpu.h   const unsigned char flstory_audiocpu[65536]
#                             snd.22 @0x0000, snd.23 @0x2000, 0x4000 bytes of
#                             real ROM; rest = 0xFF pad (sound_map's ROM
#                             window is 0x0000-0xbfff + 0xe000-0xefff
#                             diagnostic space, neither of which the real
#                             set populates past 0x4000).
#     flstory_bmcu_mcu.h   const unsigned char flstory_bmcu_mcu[2048]
#                             a45-20.mcu, verbatim (whole 0x000-0x7ff MC68705
#                             address space as dumped).
#     flstory_tilemap.h    const unsigned char flstory_tilemap[4096][8][8]
#                             8x8 chars, charlayout, 4bpp (pen 0-15), NATIVE
#                             (unrotated) MAME orientation.
#     flstory_tiles16.h    const unsigned char flstory_tiles16[1024][16][16]
#                             16x16 sprites, spritelayout, 4bpp (pen 0-15),
#                             NATIVE (unrotated) MAME orientation. NEW - see
#                             note below on why this is a separate output
#                             from the legacy flstory_tiles.h.
#
# NOT generated (hand-authored / not ROM-derived, already present, keep
# them - this script never touches them):
#     flstory_dipswitches.h - DIP config, generated separately by
#                             tools/dipswitches (dipgen.py-style) from MAME.
#     flstory_logo.h        - custom menu artwork.
#
# LEGACY OUTPUT LEFT IN PLACE, NOT REGENERATED BY THIS SCRIPT:
#     flstory_rom.h / flstory_audiocpu.h / flstory_bmcu_mcu.h were already
#     correctly produced by tools/romconv/romextract.py (verified byte-for-
#     byte against this script's own from-scratch build of the same three
#     regions while writing this script) - they are included above only so
#     this ONE script can regenerate the *entire* flstory ROM surface from
#     a bare flstory.zip in one run, per the user's request, not because
#     the old ones were wrong.
#
#     flstory_tilemap.h WAS wrong (see below) and IS regenerated here.
#     flstory_tiles.h (the old raw-bytes-only dump used for on-the-fly
#     sprite decode in flstory.cpp) is LEFT AS-IS by this script - flstory
#     .cpp currently decodes sprites straight out of that raw array at blit
#     time using its own copy of the planar math, not from a new
#     flstory_tiles16.h. flstory_tiles16.h is emitted here as an
#     INDEPENDENT, pre-decoded reference/fallback (same tiles, already
#     unpacked to pens) in case a future revision of flstory.cpp prefers a
#     precomputed table over runtime decode - see the two concrete bugs
#     below for why flstory_tiles.h's raw bytes cannot be trusted verbatim
#     without the INVERT step every consumer of it must now apply.
#
# TWO CONCRETE BUGS FOUND IN THE EXISTING (romextract.py-generated) DATA,
# FIXED HERE:
#   1. flstory_tilemap.h used tools/romconv/romextract.py's GENERIC
#      "gfx_8x8x4_planar" auto-tilemap layout (4 equal quarters of the
#      region, 1 byte/row/plane). flstory's REAL MAME charlayout is
#      different: RGN_FRAC(1,2) (region split in HALF, not quarters), with
#      2 planes per half packed as adjacent nibbles in the SAME byte
#      ({RGN_FRAC(1,2)+0, RGN_FRAC(1,2)+4, 0, 4} - i.e. bit-offset +4 within
#      a byte selects the "other" plane of that half, not a separate
#      region span). Verified empirically: the old (wrong) header decodes
#      to near-blank noise at the known font-tile range; this script's
#      literal transcription of MAME's charlayout (mame_decode() below,
#      called with flstory's own plane/xoffs/yoffs, NOT the generic
#      gfx_8x8x4_planar ones) decodes recognisable glyphs there instead.
#      tools/romconv/romextract.py itself is NOT changed by this script
#      (out of scope here) - it will still mis-decode any future game
#      whose tile ROM uses this same half-split nibble-pair packing instead
#      of the 4-equal-quarters layout it assumes.
#   2. flstory_tiles.h (raw bytes) is the "tiles" ROM_REGION concatenated
#      WITHOUT applying ROMREGION_INVERT - verified byte-for-byte against
#      the source zip (vid-a45.18 offset 0x40 = 2C 50 2C 90 ... in BOTH the
#      raw ROM file and flstory_tiles.h, i.e. NOT inverted, even though
#      MAME's ROM_START flags this exact region ROMREGION_INVERT and XORs
#      every byte with 0xFF before gfxdecode/anything else ever reads it).
#      This script's own tile/sprite builders (build_tiles/build_sprites
#      below) apply the XOR 0xFF themselves before decoding, so
#      flstory_tilemap.h and flstory_tiles16.h emitted here are correct.
#      flstory_tiles.h is left untouched (see note above) - any code
#      (including flstory.cpp's current runtime sprite decoder) reading
#      pens/bits out of it directly MUST XOR each byte with 0xFF first, or
#      apply the invert once into its own copy, to get MAME-correct pixels.
#
# MAME reference: src/mame/taito/flstory.cpp (driver by Nicola Salmoria)
#   Z80 main @ 10.733_MHz_XTAL/2, Z80 audio @ 8_MHz_XTAL/2, MC68705P5 MCU
#   @ 18.432_MHz_XTAL/6, AY-8910(YM2149) @ 8MHz/4, MSM5232 @ 8MHz/4.
#   charlayout   8,8    RGN_FRAC(1,2) 4bpp planes {RF(1,2)+0,RF(1,2)+4,0,4}
#                xoffs {3,2,1,0, 8+3,8+2,8+1,8+0}  yoffs {0*16..7*16}  inc 16*8
#   spritelayout 16,16  RGN_FRAC(1,2) 4bpp planes {RF(1,2)+0,RF(1,2)+4,0,4}
#                xoffs {3,2,1,0, 8+3,8+2,8+1,8+0, 16*8+3,16*8+2,16*8+1,16*8+0,
#                       16*8+8+3,16*8+8+2,16*8+8+1,16*8+8+0}
#                yoffs {0*16..7*16, 16*16..23*16}  inc 64*8
#   get_tile_info   tile_number = code + ((attr&0xc0)<<2) + 0x400 + 0x800*char_bank
#                   color = attr&0x0f ; flipyx = (attr&0x18)>>3
#                   category (priority group) = (attr>>5)&1
#   flstory_draw_sprites  code = spriteram[o+2] + ((spriteram[o+1]&0x30)<<4)
#                         color = spriteram[o+1]&0x0f ; flipx=b6 flipy=b7 of
#                         spriteram[o+1] ; transparent pen 15
# ============================================================

from __future__ import annotations

import argparse
import sys
import zipfile
import zlib
from pathlib import Path

# --- MAME `flstory` (parent) ROM manifest: name -> (size, CRC32) ----------
# Cross-checked against source/src/machines/flstory/crc_check.txt and MAME's
# own ROM_START(flstory) CRC values (src/mame/taito/flstory.cpp).
ROMS = {
    # maincpu (ROM_REGION 0x10000; only 0x0000-0xbfff is ROM)
    "cpu-a45.15": (0x4000, 0xF03FC969),
    "cpu-a45.16": (0x4000, 0x311AA82E),
    "cpu-a45.17": (0x4000, 0xA2B5D17D),
    # audiocpu (ROM_REGION 0x10000; only 0x0000-0x3fff is ROM)
    "snd.22": (0x2000, 0xD58B201D),
    "snd.23": (0x2000, 0x25E7FD9D),
    # bmcu:mcu (ROM_REGION 0x0800, the whole MC68705P5 address space)
    "a45-20.mcu": (0x0800, 0x7D2CDD9B),
    # tiles (ROM_REGION 0x20000, ROMREGION_INVERT) - 8 x 0x4000, RGN_FRAC(1,2)
    "vid-a45.18": (0x4000, 0x6F08F69E),  # 0x00000  half 1, quarter 0
    "vid-a45.06": (0x4000, 0xDC856A75),  # 0x04000  half 1, quarter 1
    "vid-a45.08": (0x4000, 0xD0B028CA),  # 0x08000  half 1, quarter 2
    "vid-a45.20": (0x4000, 0x1B0EDF34),  # 0x0c000  half 1, quarter 3
    "vid-a45.19": (0x4000, 0x2B572DC9),  # 0x10000  half 2, quarter 0
    "vid-a45.07": (0x4000, 0xAA4B0762),  # 0x14000  half 2, quarter 1
    "vid-a45.09": (0x4000, 0x8336BE58),  # 0x18000  half 2, quarter 2
    "vid-a45.21": (0x4000, 0xFC382BD1),  # 0x1c000  half 2, quarter 3
}


# --------------------------------------------------------------------------
class RomSource:
    """Reads the flstory ROM files either from a .zip or a loose directory,
    with size + CRC32 verification against the MAME manifest above."""

    def __init__(self, path: Path, verify: bool):
        self.verify = verify
        if path.is_dir():
            self.zip = None
            self.dir = path
            self.label = str(path)
        elif zipfile.is_zipfile(path):
            self.zip = zipfile.ZipFile(path, "r")
            self.dir = None
            self.label = str(path)
            self._members = {Path(n).name.lower(): n for n in self.zip.namelist()}
        else:
            sys.exit(f"ERROR: {path} is neither a directory nor a zip archive")

    def _raw(self, name: str) -> bytes:
        if self.zip is not None:
            member = self._members.get(name.lower())
            if member is None:
                sys.exit(f"ERROR: {name} not found in {self.label}")
            return self.zip.read(member)
        p = self.dir / name
        if not p.exists():
            sys.exit(f"ERROR: missing {name} in {self.label}")
        return p.read_bytes()

    def load(self, name: str) -> bytes:
        """Read one ROM, checking size and (optionally) CRC32."""
        size, crc = ROMS[name]
        b = self._raw(name)
        if len(b) != size:
            sys.exit(f"ERROR: {name}: expected {size} bytes, got {len(b)}")
        if self.verify:
            got = zlib.crc32(b) & 0xFFFFFFFF
            if got != crc:
                sys.exit(
                    f"ERROR: {name}: CRC32 0x{got:08X}, expected 0x{crc:08X}. "
                    f"Wrong or bad dump (run `mame flstory -verifyroms`), or "
                    f"pass --no-verify to override."
                )
        return b


# --- generic MAME planar gfx decoder --------------------------------------
# planes / xoffs / yoffs are ABSOLUTE BIT offsets into `data`, exactly like
# gfx_element::decode() in src/emu/drawgfx.cpp. planes[0] is the
# most-significant pen bit, planes[-1] the least. MAME reads bit b of byte B
# as MSB-first: (data[B] >> (7 - b)) & 1.
def mame_decode(data: bytes, width: int, height: int, planes: list[int],
                xoffs: list[int], yoffs: list[int], bits_per_tile: int,
                count: int, base_bit: int = 0) -> list[list[list[int]]]:
    tiles = []
    for t in range(count):
        base = base_bit + t * bits_per_tile
        tile = []
        for y in range(height):
            row = []
            for x in range(width):
                v = 0
                for p in planes:
                    off = base + yoffs[y] + xoffs[x] + p
                    bit = (data[off >> 3] >> (7 - (off & 7))) & 1
                    v = (v << 1) | bit
                row.append(v)
            tile.append(row)
        tiles.append(tile)
    return tiles


# --------------------------------------------------------------------------
def build_maincpu(rs: RomSource) -> bytes:
    """MAME ROM_REGION 0x10000 "maincpu": cpu-a45.15 @0x0000, .16 @0x4000,
    .17 @0x8000 (0xc000 bytes of real ROM). 0xc000-0xffff is never loaded
    (the CPU map's ROM window is only 0x0000-0xbfff) - padded 0xFF."""
    cpu = bytearray(b"\xFF" * 0x10000)
    cpu[0x0000:0x4000] = rs.load("cpu-a45.15")
    cpu[0x4000:0x8000] = rs.load("cpu-a45.16")
    cpu[0x8000:0xC000] = rs.load("cpu-a45.17")
    return bytes(cpu)


def build_audiocpu(rs: RomSource) -> bytes:
    """MAME ROM_REGION 0x10000 "audiocpu": snd.22 @0x0000, snd.23 @0x2000
    (0x4000 bytes of real ROM). sound_map's ROM window is 0x0000-0xbfff plus
    a diagnostic-ROM space at 0xe000-0xefff, neither populated here past
    0x4000 - padded 0xFF."""
    cpu = bytearray(b"\xFF" * 0x10000)
    cpu[0x0000:0x2000] = rs.load("snd.22")
    cpu[0x2000:0x4000] = rs.load("snd.23")
    return bytes(cpu)


def build_bmcu(rs: RomSource) -> bytes:
    """MAME ROM_REGION 0x0800 "bmcu:mcu": a45-20.mcu, verbatim - the whole
    MC68705P5 0x000-0x7ff address space exactly as dumped."""
    return rs.load("a45-20.mcu")


def build_tiles_region(rs: RomSource) -> bytes:
    """MAME ROM_REGION(0x20000, "tiles", ROMREGION_INVERT):
        vid-a45.18 @0x00000  vid-a45.06 @0x04000
        vid-a45.08 @0x08000  vid-a45.20 @0x0c000
        vid-a45.19 @0x10000  vid-a45.07 @0x14000
        vid-a45.09 @0x18000  vid-a45.21 @0x1c000
    ROMREGION_INVERT means MAME XORs every byte of the assembled region with
    0xFF AFTER loading, before gfxdecode (or anything else) reads it - see
    src/emu/romload.cpp's region-post-process step. This step was MISSING
    from the existing tools/romconv/romextract.py-generated flstory_tiles.h
    (verified byte-for-byte against the raw zip: identical, un-inverted) -
    applied here so flstory_tilemap.h / flstory_tiles16.h decode to the
    actual MAME pixel values."""
    region = bytearray()
    for name in ("vid-a45.18", "vid-a45.06", "vid-a45.08", "vid-a45.20",
                 "vid-a45.19", "vid-a45.07", "vid-a45.09", "vid-a45.21"):
        region += rs.load(name)
    assert len(region) == 0x20000, len(region)
    return bytes(b ^ 0xFF for b in region)


def build_chars(region: bytes) -> list[list[list[int]]]:
    """charlayout, GFXDECODE gfx[0] ("tiles", palette base 0, 16 colors):
        8,8  RGN_FRAC(1,2)  4 planes
        planeoffset { RGN_FRAC(1,2)+0, RGN_FRAC(1,2)+4, 0, 4 }
                       ^MSB (2nd half, hi nibble)      ^LSB (1st half, lo nibble)
        xoffs { 3,2,1,0, 8+3,8+2,8+1,8+0 }
        yoffs { 0*16, 1*16, ... 7*16 }
        charincrement 16*8

    region = the full inverted "tiles" ROM_REGION (0x20000), split by
    RGN_FRAC(1,2) into two 0x10000 halves. count = (0x10000*8)/(16*8) = 4096,
    matching get_tile_info's max tile_number = code + ((attr&0xc0)<<2) +
    0x400 + 0x800*char_bank = up to 0xFFF (4096 tiles)."""
    rf = len(region) * 8 // 2                        # RGN_FRAC(1,2) in bits
    planes = [rf + 0, rf + 4, 0, 4]                  # MSB .. LSB
    xoffs = [3, 2, 1, 0, 8 + 3, 8 + 2, 8 + 1, 8 + 0]
    yoffs = [y * 16 for y in range(8)]
    bpt = 16 * 8
    count = rf // bpt
    assert count == 4096, count
    return mame_decode(region, 8, 8, planes, xoffs, yoffs, bpt, count)


def build_sprites16(region: bytes) -> list[list[list[int]]]:
    """spritelayout, GFXDECODE gfx[1] ("tiles", palette base 256, 16 colors):
        16,16  RGN_FRAC(1,2)  4 planes  (same region/planes as charlayout)
        xoffs { 3,2,1,0, 8+3,8+2,8+1,8+0,
                16*8+3,16*8+2,16*8+1,16*8+0, 16*8+8+3,16*8+8+2,16*8+8+1,16*8+8+0 }
        yoffs { 0*16..7*16, 16*16..23*16 }
        charincrement 64*8

    Same 0x20000 inverted region as build_chars(), decoded as 16x16 instead
    of 8x8. count = (0x10000*8)/(64*8) = 1024, matching flstory's 10-bit
    sprite code (spriteram[o+2] + ((spriteram[o+1]&0x30)<<4) = 0..0x3ff)."""
    rf = len(region) * 8 // 2
    planes = [rf + 0, rf + 4, 0, 4]
    xoffs = ([3, 2, 1, 0, 8 + 3, 8 + 2, 8 + 1, 8 + 0] +
             [16 * 8 + 3, 16 * 8 + 2, 16 * 8 + 1, 16 * 8 + 0,
              16 * 8 + 8 + 3, 16 * 8 + 8 + 2, 16 * 8 + 8 + 1, 16 * 8 + 8 + 0])
    yoffs = [y * 16 for y in range(8)] + [y * 16 for y in range(16, 24)]
    bpt = 64 * 8
    count = rf // bpt
    assert count == 1024, count
    return mame_decode(region, 16, 16, planes, xoffs, yoffs, bpt, count)


# --- header writers ------------------------------------------------------
BANNER = "// Generated by flstory_romconv_all.py from the MAME `flstory` (parent) ROM set. Do not edit.\n"


def write_bytes_header(path: Path, guard: str, sym: str, data: bytes,
                        note: str, size_define: str | None = None) -> None:
    with path.open("w") as f:
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(BANNER)
        f.write(f"// {note}\n\n")
        f.write(f"const unsigned char {sym}[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",\n")
        f.write("};\n\n")
        if size_define:
            f.write(f"#define {size_define} {len(data)}\n")
        f.write("#endif\n")
    print(f"  wrote {path.name:24s} {len(data):#9x} bytes")


def write_tiles_header(path: Path, guard: str, sym: str, tiles: list, dim: int, note: str) -> None:
    with path.open("w") as f:
        f.write(f"#ifndef {guard}\n#define {guard}\n\n")
        f.write(BANNER)
        f.write(f"// {note}\n")
        f.write(f"// {len(tiles)} tiles, {dim}x{dim} pixels, ROT0 (natural, unrotated MAME "
                f"orientation - screen rotation for flstory's ROT180 cabinet is entirely "
                f"the renderer's problem (flstory.cpp), not this table's).\n\n")
        f.write(f"const unsigned char {sym}[{len(tiles)}][{dim}][{dim}] = {{\n")
        for i, t in enumerate(tiles):
            rows = ["{" + ",".join(str(v) for v in t[y]) + "}" for y in range(dim)]
            f.write("  {" + ",".join(rows) + "}")
            f.write(",\n" if i < len(tiles) - 1 else "\n")
        f.write("};\n\n#endif\n")
    print(f"  wrote {path.name:24s} {len(tiles)} tiles ({dim}x{dim})")


# --- optional PNG preview ----------------------------------------------
def preview(chars, sprites, outpng: Path) -> None:
    try:
        from PIL import Image
    except ImportError:
        print("  (PIL not installed - skipping preview)")
        return

    PAL = [(20 + i * 14, 20 + i * 10, 220 - i * 12) for i in range(16)]

    def block(ts, dim, cols):
        rows = (len(ts) + cols - 1) // cols
        img = Image.new("RGB", (cols * (dim + 1), rows * (dim + 1)), (32, 32, 96))
        px = img.load()
        for i, t in enumerate(ts):
            ox, oy = (i % cols) * (dim + 1), (i // cols) * (dim + 1)
            for y in range(dim):
                for x in range(dim):
                    px[ox + x, oy + y] = PAL[t[y][x] & 15]
        return img

    # chars: only preview the first 1024 (font/UI range) to keep the image sane
    parts = [block(chars[:1024], 8, 48), block(sprites, 16, 32)]
    W = max(p.width for p in parts)
    H = sum(p.height + 6 for p in parts)
    img = Image.new("RGB", (W, H), (0, 0, 0))
    y = 0
    for p in parts:
        img.paste(p, (0, y))
        y += p.height + 6
    img = img.resize((img.width * 2, img.height * 2), Image.NEAREST)
    img.save(outpng)
    print(f"  wrote {outpng.name} (preview)")


# --------------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(description="Convert the MAME `flstory` (parent) ROM set to flstory headers.")
    ap.add_argument("romsrc", nargs="?", default=None,
                    help="flstory.zip or a folder of loose ROM files "
                         "(default: GalaginoPlus-main/romszip/flstory.zip)")
    ap.add_argument("-o", "--outdir", default=None,
                    help="output folder for the .h files (default: this script's own directory)")
    ap.add_argument("--no-verify", action="store_true", help="skip CRC32 checks")
    ap.add_argument("--no-preview", action="store_true", help="do not write the PNG preview")
    args = ap.parse_args()

    # this script lives in GalaginoPlus-main/source/src/machines/flstory/ ;
    # walk up 4 levels to the repo root (flstory -> machines -> src -> source
    # -> repo root, i.e. GalaginoPlus-main).
    here = Path(__file__).resolve().parent
    root = here.parents[3]
    romsrc = (Path(args.romsrc).resolve() if args.romsrc
              else (root / "romszip" / "flstory.zip").resolve())
    outdir = Path(args.outdir).resolve() if args.outdir else here

    if not romsrc.exists():
        sys.exit(f"ERROR: ROM source {romsrc} does not exist")
    outdir.mkdir(parents=True, exist_ok=True)

    verify = not args.no_verify
    print(f"ROMs : {romsrc}")
    print(f"out  : {outdir}")
    print(f"CRC verify: {'on' if verify else 'OFF'}\n")

    rs = RomSource(romsrc, verify)

    write_bytes_header(outdir / "flstory_rom.h", "_FLSTORY_ROM_H_",
                       "flstory_rom", build_maincpu(rs),
                       "Z80 main CPU ROM space image (0x10000). cpu-a45.15 @0x0000, "
                       ".16 @0x4000, .17 @0x8000 (0xc000 bytes of real code); "
                       "0xc000-0xffff = 0xFF pad (never fetched - the CPU map's ROM "
                       "window is only 0x0000-0xbfff).",
                       "FLSTORY_ROM_SIZE")
    write_bytes_header(outdir / "flstory_audiocpu.h", "_FLSTORY_AUDIOCPU_H_",
                       "flstory_audiocpu", build_audiocpu(rs),
                       "Z80 audio CPU ROM space image (0x10000). snd.22 @0x0000, "
                       "snd.23 @0x2000 (0x4000 bytes of real code); rest = 0xFF pad "
                       "(sound_map's ROM window is 0x0000-0xbfff + a diagnostic space "
                       "at 0xe000-0xefff, neither populated here past 0x4000).",
                       "FLSTORY_AUDIOCPU_SIZE")
    write_bytes_header(outdir / "flstory_bmcu_mcu.h", "_FLSTORY_BMCU_MCU_H_",
                       "flstory_bmcu_mcu", build_bmcu(rs),
                       "MC68705P5 protection MCU ROM, a45-20.mcu verbatim (whole "
                       "0x000-0x7ff address space as dumped).",
                       "FLSTORY_BMCU_MCU_SIZE")

    tiles_region = build_tiles_region(rs)   # already INVERTed (XOR 0xFF), see build_tiles_region()
    chars = build_chars(tiles_region)
    sprites16 = build_sprites16(tiles_region)

    write_tiles_header(outdir / "flstory_tilemap.h", "FLSTORY_TILEMAP_H",
                       "flstory_tilemap", chars, 8,
                       "Background/foreground chars decoded from the 'tiles' ROM region "
                       "(8 x vid-a45.* chips, ROMREGION_INVERT applied), charlayout, "
                       "4bpp (pen 0-15): flstory_tilemap[tile_number][y][x]. "
                       "get_tile_info: tile_number = code + ((attr&0xc0)<<2) + 0x400 + "
                       "0x800*char_bank; color = attr&0x0f; flipyx = (attr&0x18)>>3; "
                       "priority category (bg split) = (attr>>5)&1. Replaces the "
                       "previous flstory_tilemap.h, which used romextract.py's generic "
                       "gfx_8x8x4_planar auto-layout - WRONG for this ROM's actual "
                       "RGN_FRAC(1,2) half-split nibble-pair packing (see this script's "
                       "header comment, 'concrete bug #1').")
    write_tiles_header(outdir / "flstory_tiles16.h", "FLSTORY_TILES16_H",
                       "flstory_tiles16", sprites16, 16,
                       "16x16 sprites decoded from the SAME 'tiles' ROM region as "
                       "flstory_tilemap.h (ROMREGION_INVERT already applied here), "
                       "spritelayout, 4bpp (pen 0-15, pen 15 transparent): "
                       "flstory_tiles16[code][y][x]. flstory_draw_sprites: code = "
                       "spriteram[o+2] + ((spriteram[o+1]&0x30)<<4); color = "
                       "spriteram[o+1]&0x0f; flipx/flipy = bit6/bit7 of spriteram[o+1]. "
                       "NEW pre-decoded table - flstory.cpp currently decodes sprites "
                       "at blit time straight from the raw (legacy, NON-inverted) "
                       "flstory_tiles.h instead; see this script's header comment for "
                       "why both exist and what a consumer of the raw table must still "
                       "do (XOR 0xFF) to get correct pixels.")

    if not args.no_preview:
        preview(chars, sprites16, here / "flstory_gfx_preview.png")

    print("\ndone.")


if __name__ == "__main__":
    main()
